#!/usr/bin/env bash
# Start Chrome with remote debugging enabled for SubStretcher
# Generated by install.sh

echo "Starting Chrome with remote debugging on port 9222..."
echo "Close all Chrome windows first if Chrome is already running."
echo ""

"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" --remote-debugging-port=9222 &

echo ""
echo "Chrome started. You can now run: substretcher status"
