#!/usr/bin/env bash
# Start Chrome with remote debugging enabled for SubStretcher
# Generated by install.sh

echo "Starting Chrome with remote debugging on port 9222..."
echo ""

# Use a separate Chrome profile to allow debugging even when Chrome is already running
CHROME_PROFILE="$HOME/.substretcher/chrome-profile"
mkdir -p "$CHROME_PROFILE"

"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" \
  --remote-debugging-port=9222 \
  --user-data-dir="$CHROME_PROFILE" &

echo ""
echo "Chrome started with debug profile at: $CHROME_PROFILE"
echo "You can now run: substretcher status"
